# TrueLayer

###
# @name Get banks

< {%
  client.global.clearAll()
%}

GET {{API_URL}}/api/providers/top?country=RO&count=20
Content-Type: application/json
x-api-key: {{api_key}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 %}

###
# @name Initiate payment

POST {{API_URL}}/api/payments?x-api-key={{api_key}}
Content-Type: application/json
x-api-key: {{api_key}}

< data/payment_create.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    // let qrCodeLink = jsonPath(response.body, "$.shortLinkUrls.qrCodeLink")
    // client.global.set("qrCodeLink",  qrCodeLink);
 %}
###
# @name Initiate payment short links

POST {{API_URL}}/api/payments/short-links
Content-Type: application/json
x-api-key: {{api_key}}

< data/payment_short_links.json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    let qrCodeLink = jsonPath(response.body, "$.shortLinkUrls.qrCodeLink")
    client.global.set("qrCodeLink",  qrCodeLink);
 %}
###
# @name GET QR code payment short link
# use test IBAN: GB33BUKB20201555555555

GET {{qrCodeLink}}
Content-Type: application/json
x-api-key: {{api_key}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 %}

###
# @name GET payments

GET {{API_URL}}/api/payments?datefrom=2025-05-15&Limit=3
Content-Type: application/json
x-api-key: {{api_key}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 %}
###
# @name GET payment status

GET {{API_URL}}/api/payments/d09f5c08-b038-4ac4-951b-8f1d16faaa6b
Content-Type: application/json
x-api-key: {{api_key}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
 %}
