jwt:
  private.key: classpath:app.key
  public.key:  classpath:app.pub
spring:
  datasource:
    username: modulith
    password: modulith
    url: jdbc:postgresql://localhost:5432/splitmate
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
    show-sql: true
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true
logging:
  level:
    ro.splitmate: DEBUG
    org.springframework.modulith: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info